services:
  mysql-service:
    image: mysql/mysql-server:8.0.32-1.2.11-server
    command:
      - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --skip-ssl
    container_name: 'mysql-service'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - fiap-carros-network
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prodrigo@1988" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=rodrigo@1988
      - MYSQL_DATABASE=fiap_carros
      - MYSQL_ROOT_HOST=127.0.0.1
    ports:
      - "3306:3306"

  fiap-carros:
    image: rodrigoamora/rodrigo-springboot:latest
    container_name: 'fiap-carros'
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/fiap_carros?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rodrigo@1988
      SPRING_PROFILES_ACTIVE: prod
      JAVA_TOOL_OPTIONS: -Xmx512m -Xms256m
    networks:
      - fiap-carros-network
    restart: always
    depends_on:
      mysql-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  fiap-carros-network:
    driver: bridge

volumes:
  mysql-data:
