version: "3.9"
services:
  mysql-service:
    image: mysql/mysql-server:8.0.32-1.2.11-server
    command: --default-authentication-plugin=mysql_native_password
    container_name: 'mysql-server'
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
      - ./log/mysql:/var/log/mysql:rw
    networks:
      - spring-boot-mysql-network
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=rodrigo@1988
      - MYSQL_DATABASE=fiap_carros
      - MYSQL_ROOT_HOST=127.0.0.1
    ports:
      - "3306:3306"
    expose:
      - '3306'
      -
  fiap-carros:
    image: rodrigoamora/rodrigo-springboot:latest
    container_name: 'fiap-carros'
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/fiap_carros?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rodrigo@1988
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - spring-boot-mysql-network
    depends_on:
      - mysql-service

networks:
  spring-boot-mysql-network:
    driver: bridge
